"""update models style and constraints

Revision ID: 338805a31d08
Revises: 377e7d79e54c
Create Date: 2026-09-07 11:54:12.872757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338805a31d08'
down_revision: Union[str, Sequence[str], None] = '377e7d79e54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_wishlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_wishlist')
    )
    with op.batch_alter_table('user_wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_wishlist_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_wishlist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artworks_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artworks_game_id'), ['game_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_thread_id'), ['thread_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussions_game_id'), ['game_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('game_banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_banners_game_id'), ['game_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('game_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_media_game_id'), ['game_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('game_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_reviews_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_reviews_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reactions_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_reactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'game_reviews', ['review_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_role_id'))

    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_reviews', ['review_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_review_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_reactions_review_id'))

    with op.batch_alter_table('game_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_game_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_reviews_game_id'))

    with op.batch_alter_table('game_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_game_media_game_id'))

    with op.batch_alter_table('game_banners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_game_banners_game_id'))

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_discussions_game_id'))
        batch_op.drop_index(batch_op.f('ix_discussions_author_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_comments_thread_id'))
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])
        batch_op.create_foreign_key(None, 'comment_threads', ['thread_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_artworks_game_id'))
        batch_op.drop_index(batch_op.f('ix_artworks_author_id'))

    with op.batch_alter_table('user_wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_wishlist_product_id'))

    op.drop_table('user_wishlist')
    # ### end Alembic commands ###
