"""add_achievements_and_update_games

Revision ID: a50e9797114c
Revises: deab3e08bac9
Create Date: 2026-09-06 11:34:15.380708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50e9797114c'
down_revision: Union[str, Sequence[str], None] = 'deab3e08bac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

        batch_op.add_column(sa.Column('rating', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_info', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('meta_info')
        batch_op.drop_column('requirements')
        batch_op.drop_column('rating')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
