"""update game review artwork models

Revision ID: deab3e08bac9
Revises: 70f8e3835b64
Create Date: 2026-09-02 18:02:20.311837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deab3e08bac9'
down_revision: Union[str, Sequence[str], None] = '70f8e3835b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('game_reviews', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('games', 'download_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('download_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('game_reviews', 'updated_at')
    op.drop_column('artworks', 'updated_at')
    # ### end Alembic commands ###
